apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: postgres-service
    app: domo-voting-app
spec:
  selector:
    name: postgres-pod
    app: demo-voting-app
  ports:
    - name: postgres-port
      port: 6379
      targetPort: 6379
