apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: domo-voting-app
spec:
  selector:
    name: redis-pod
    app: demo-voting-app
  ports:
    - name: redis-port
      port: 6379
      targetPort: 6379
